name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'playwright.config.*'
      - '.github/workflows/ci.yml'

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  smoke:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Install Playwright Chromium only
        run: npx playwright install --with-deps chromium

      - name: Enforce screenshot hygiene
        run: node scripts/screenshot-hygiene.mjs --ci

      - name: Run smoke tests (chromium)
        env:
          SMOKE_URL: ${{ vars.SMOKE_URL || '' }}
        run: npx playwright test tests/e2e/smoke.spec.ts --project=chromium --reporter=line

      - name: Upload Playwright artifacts (optional)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore


