name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'playwright.config.*'
      - '.github/workflows/ci.yml'

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  smoke:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Install Playwright Chromium only
        run: npx playwright install --with-deps chromium

      - name: Enforce screenshot hygiene
        run: node scripts/screenshot-hygiene.mjs --ci

      - name: Run smoke tests (chromium)
        env:
          SMOKE_URL: ${{ vars.SMOKE_URL || '' }}
        run: npx playwright test tests/e2e/smoke.spec.ts --project=chromium --reporter=line

      - name: Upload Playwright artifacts (optional)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

name: ci

on:
  pull_request:
    types: [ready_for_review, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.ts'
      - 'tailwind.config.js'
      - 'playwright-screenshots.mjs'
      - 'screens/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --no-audit --no-fund
      - run: npm run lint --if-present

  typecheck:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --no-audit --no-fund
      - run: npx tsc --noEmit --pretty false || true

  build:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --no-audit --no-fund
      - run: npm run build --if-present

  e2e_screens:
    name: Preview and screenshots
    needs: [build]
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --no-audit --no-fund
      - run: npx playwright install --with-deps chromium
      - run: npx vite preview --host 127.0.0.1 --strictPort --port 4173 & npx wait-on --timeout 120000 http://127.0.0.1:4173
      - run: PREVIEW_URL=http://127.0.0.1:4173 node playwright-screenshots.mjs || true
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screens

name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Typecheck (non-blocking)
        run: npm run typecheck --if-present || true
      - name: Build
        run: npm run build --if-present
      - name: Unit tests
        run: npm test --if-present -- --run
      - name: PR screenshots (non-blocking)
        run: node playwright-screenshots.mjs || true
      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screens


